### PR TITLE
Quick first pass of some stuff

### PR DESCRIPTION
**Pull request by robneu**
Feel free to take or leave anything in this. I haven't messed with the actual query at all yet. Let me know if you have any questions about any of it or find any issues. I only did really quick testing, so there may be bugs.

### CODE REVIEW

**Comment by bradpotter** [comment]
Appreciate it. I'm making changes locally once I understand the reasoning and pushing via my GitHub desktop client. I couldn't figure out how to get GitHub Desktop to see your PR. Really appreciate you taking a look! I also uploaded my latest loop.

**Comment by bradpotter** [comment]
Ok, all changes made with exception of using template_include instead of template_redirect in https://github.com/robneu/genesis-page-templates/commit/c3a5ad25b53139d40a05d10b8d7c8c975da767dc

template_include causes white screen

I did make a few changes in the associated function however "require_once" was needed - $template = require_once plugin_dir_path blah blah

As I mentioned earlier I uploaded my latest loop. Also the admin has a couple of fields to control post info & post meta. I will need to address this when using custom post types.

I will be converting some other fields to select menus. Also will be attempting to accommodate multiple entries for post type, tax & term if that doesn't make my head explode.

**Comment by robneu** [comment]
`template_include` definitely doesn't cause a white screen with the code I sent and that's the correct hook for loading this template. It looks like you're still missing the call to `genesis()` so that may be the reason it's white screening for you when you use that hook.

The way you're doing it now, WordPress is still loading `page.php` from Genesis core after you include your template, so `genesis()` is fired there rather than within your template. That could cause unexpected weirdness on some custom child themes that have their own `page.php` file. You want to avoid loading that template and make sure yours is the one true template for that page.

`template_redirect` should really only be used when you have to fire an actual WordPress redirect for some reason. Mark Jaquith [wrote about this](https://markjaquith.wordpress.com/2014/02/19/template_redirect-is-not-for-loading-templates/) a while back. It's an older post, but still probably worth a read. 

You wouldn't require the file in that hook either, the template gets loaded elsewhere. You just need to overwrite the `$template` variable with the absolute path to the template that you want to load and then return that. WordPress will handle the actual file include.

**Comment by robneu** [comment]
One other thing worth noting is that when you're loading a "template" file you probably wouldn't want to use `require`, `require_once`, `include`, or `include_once` directly. WordPress [has a special function](https://codex.wordpress.org/Function_Reference/load_template) for loading templates. `load_template` will inject all of the standard template variables before loading the file. If those variables are missing, developers might have trouble figuring out why they can't access them from within your template.

In this case, you don't need to worry about it because you're just filtering a path that gets loaded later by `load_template`, but if you ever need to include a template outside of WordPress' default template loading methods that's the function you'd want to use.

**Comment by bradpotter** [comment]
Ack! Your right I missed the Genesis call. My rookie mistake. I'll add the call and go back and change to template_include and test again. Thanks for the detailed explanation and your help.

**Pull request closed without merging**
